import React, { useState } from "react";
import Head from "next/head";
import Tab1 from "../components/tab/tab1";
import Header from "../components/Header";

export default function Home() {
  const tabArray = ["aaa", "bbb", "ccc", "ddd"];
  const [tab, setTab] = useState(tabArray[0]);

  const handleClickTab = (e) => {
    console.log(e.target.innerHTML);
    setTab(e.target.innerHTML);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="mt-4 flex flex-col gap-2">
        <Tab1 />
        <hr className="w-2/3 mx-auto border-b-2 border-gray-600" />
        <Tab1 />
        <hr className="w-2/3 mx-auto border-b-2 border-gray-600" />
      </div>
    </div>
  );
}
