import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import Link from "next/link";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="flex mt-5 mx-5 gap-3">
        <Link href="/buttons">
          <a className=" h-40 w-64 text-center leading-[10rem] border text-5xl text-gray-500 transition hover:text-blue-300 hover:border-blue-300  ">
            Buttons
          </a>
        </Link>
        <Link href="/tabs">
          <a className=" h-40 w-64 text-center leading-[10rem] border text-5xl text-gray-500 transition hover:text-blue-300 hover:border-blue-300  ">
            Tabs
          </a>
        </Link>
      </div>
    </div>
  );
};

export default Home;
